In [ ]:
import pandas as pd
from datasets import load_dataset

dataset= load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/3.25k [00:00<?, ?B/s]

data_jobs.csv:   0%|          | 0.00/231M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/785741 [00:00<?, ? examples/s]

In [ ]:
df.describe()

                     job_posted_date  salary_year_avg  salary_hour_avg
count                         785741     22003.000000     10662.000000
mean   2023-06-25 16:02:11.860248576    123286.274072        47.016598
min              2023-01-01 00:00:04     15000.000000         8.000000
25%              2023-03-20 10:05:48     90000.000000        27.500000
50%              2023-06-29 06:11:38    115000.000000        45.980000
75%              2023-09-27 01:01:16    150000.000000        61.159996
max              2023-12-31 23:59:58    960000.000000       391.000000
std                              NaN     48312.449482        21.890738

In [ ]:
min_salary = df['salary_year_avg'].idxmin()

In [ ]:
df.iloc[min_salary]

job_title_short                                              Data Engineer
job_title                                           Data Engineer - Hadoop
job_location                                                        Brazil
job_via                                                       via LinkedIn
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                     Brazil
job_posted_date                                        2023-12-09 10:05:30
job_no_degree_mention                                                 True
job_health_insurance                                                 False
job_country                                                         Brazil
salary_rate                                                           year
salary_year_avg                                                    15000.0
salary_hour_avg                                                        NaN
company_name                                               Net2Source Inc.
job_skills               ['java', 'python', 'oracle', 'aws', 'hadoop', ...
job_type_skills          {'cloud': ['oracle', 'aws'], 'libraries': ['ha...
Name: 665729, dtype: object

In [ ]:
df['job_title_short'].value_counts()

job_title_short
Data Analyst                 196075
Data Engineer                186241
Data Scientist               172286
Business Analyst              49063
Software Engineer             44929
Senior Data Engineer          44563
Senior Data Scientist         36957
Senior Data Analyst           29216
Machine Learning Engineer     14080
Cloud Engineer                12331
Name: count, dtype: int64

In [ ]:
df.groupby('job_title_short')['salary_year_avg'].median()

job_title_short
Business Analyst              85000.0
Cloud Engineer                90000.0
Data Analyst                  90000.0
Data Engineer                125000.0
Data Scientist               127500.0
Machine Learning Engineer    106415.0
Senior Data Analyst          111175.0
Senior Data Engineer         147500.0
Senior Data Scientist        155500.0
Software Engineer             99150.0
Name: salary_year_avg, dtype: float64

In [ ]:
df.groupby('job_title_short')['salary_year_avg'].agg(['min','max','median'])

                               min       max    median
job_title_short
Business Analyst           16500.0  387460.0   85000.0
Cloud Engineer             42000.0  280000.0   90000.0
Data Analyst               25000.0  650000.0   90000.0
Data Engineer              15000.0  525000.0  125000.0
Data Scientist             27000.0  960000.0  127500.0
Machine Learning Engineer  30000.0  325000.0  106415.0
Senior Data Analyst        30000.0  425000.0  111175.0
Senior Data Engineer       35000.0  425000.0  147500.0
Senior Data Scientist      45000.0  890000.0  155500.0
Software Engineer          28000.0  375000.0   99150.0

In [ ]:
us_jobs = df[df['job_country'] == "United States"]

In [ ]:
us_jobs = us_jobs[us_jobs['salary_year_avg'].notna()]

In [ ]:
us_jobs.groupby('job_title_short')['salary_year_avg'].agg(['median','min','max', 'count']).sort_values(by='median', ascending=False)

                             median      min       max  count
job_title_short
Senior Data Scientist      155000.0  55000.0  475000.0   1241
Machine Learning Engineer  150000.0  44408.5  315000.0    128
Senior Data Engineer       150000.0  45000.0  375000.0   1058
Data Scientist             130000.0  30000.0  960000.0   4553
Software Engineer          130000.0  48982.0  375000.0    157
Data Engineer              125000.0  23496.0  525000.0   2915
Cloud Engineer             116100.0  42000.0  221844.0     20
Senior Data Analyst        110000.0  35360.0  425000.0    913
Business Analyst            90000.0  35000.0  387460.0    431
Data Analyst                90000.0  25000.0  375000.0   4350